# Generated by Django 2.2.19 on 2022-08-19 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20220815_1745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='describtion',
            new_name='description',
        ),
    ]
